jwt:
  secret-key: ${JWT_SECRET_KEY}
  key-validity: ${JWT_KEY_VALIDITY}
server:
  port: 8081
  servlet:
    context-path:
      /ambiglyph-server

spring:
  datasource:
    jdbcUrl: ${SPRING_DATASOURCE_URL}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
