jwt:
  secret-key: ${JWT_SECRET_KEY}
  key-validity: ${JWT_KEY_VALIDITY}
server:
  port: 8081
  servlet:
    context-path:
      /ambiglyph-server

spring:
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_URL}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
